name: gh-pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /myeongcheol-shin/
name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
        # 1. change path which exist lib/main.dart
        working-directory: ./question_game
      - run: |
          # 2. change path to [existed lib/main.dart path]/build/web
          cd question_game/build/web
          git init
           # 3. change your email
          git config --global user.email a36243845@gmail.com
          # 4. change your name
          git config --global user.name shino72
          git status
          # 5. change your repository
          git remote add origin https://github.com/Myeongcheol-shin/question_game
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
